//! The `Theme` colors of ui/components/theme.slint as `Color` consts (`json-key`
//! → `JSON_KEY`), generated by build.rs, for colors Rust paints itself.
#![allow(dead_code)]

include!(concat!(env!("OUT_DIR"), "/theme_colors.rs"));
